<?PHP
require_once './ASP.php';
require_once './Conn.php';
require_once './MySqlClass.php';
//更新网址          http://127.0.0.1/phpAccess.asp
?>
<?PHP


 	$conn=OpenConn(); 
	$mydbcharset = 'gbk';				//编码
 	$mydbpre="";						//表前面的前缀
	$char = ' ENGINE=MyISAM DEFAULT CHARSET='.$mydbcharset;
	$sqlTables = array(
	
	//access start
"{$mydbpre}admin" => "CREATE TABLE `{$mydbpre}admin` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(250) NOT NULL default '',
`pwd` varchar(250) NOT NULL default '',
`pseudonym` varchar(255) NOT NULL default '',
`adminlevel` varchar(250) NOT NULL default '',
`channel` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`regip` varchar(250) NOT NULL default '',
`upip` varchar(250) NOT NULL default '',
`quanxian` varchar(250) NOT NULL default '',
`verificationmode` varchar(250) NOT NULL default '',
`mtest` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}articledetail" => "CREATE TABLE `{$mydbpre}articledetail` (
`id` int(5) unsigned NOT NULL auto_increment,
`parentid` varchar(250) NOT NULL default '',
`topid` varchar(250) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` varchar(250) NOT NULL default '',
`smallimage` varchar(250) NOT NULL default '',
`bigimage` varchar(250) NOT NULL default '',
`bannerimage` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`titlecolor` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`ischeck` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`occasions` varchar(250) NOT NULL default '',
`hotline` varchar(250) NOT NULL default '',
`model` varchar(250) NOT NULL default '',
`author` varchar(250) NOT NULL default '',
`articlesource` varchar(250) NOT NULL default '',
`price` varchar(250) NOT NULL default '',
`newprice` varchar(250) NOT NULL default '',
`memberprice` varchar(250) NOT NULL default '',
`sold` varchar(250) NOT NULL default '',
`membertype` varchar(250) NOT NULL default '',
`memberuser` varchar(250) NOT NULL default '',
`hits` varchar(250) NOT NULL default '',
`titlealt` varchar(250) NOT NULL default '',
`bigfilesalt` varchar(250) NOT NULL default '',
`smallfilesalt` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`productabout` varchar(250) NOT NULL default '',
`articledescription` varchar(250) NOT NULL default '',
`httpurl` varchar(250) NOT NULL default '',
`recordurl` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`ncount` varchar(250) NOT NULL default '',
`articleinfostyle` varchar(250) NOT NULL default '',
`articleinfophotowidth` varchar(250) NOT NULL default '',
`articleinfophotoheight` varchar(250) NOT NULL default '',
`relatedtags` varchar(250) NOT NULL default '',
`weight` int(8) NOT NULL default '0',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`noteinfo` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}bidding" => "CREATE TABLE `{$mydbpre}bidding` (
`id` int(5) unsigned NOT NULL auto_increment,
`searchwords` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`showreason` varchar(250) NOT NULL default '',
`ncomputersearch` varchar(250) NOT NULL default '',
`nmobliesearch` varchar(250) NOT NULL default '',
`ncountsearch` varchar(250) NOT NULL default '',
`nwordprice` varchar(250) NOT NULL default '',
`ndegree` varchar(250) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}bigclass" => "CREATE TABLE `{$mydbpre}bigclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(250) NOT NULL default '',
`articlepagesize` varchar(250) NOT NULL default '',
`articleinfostyle` varchar(250) NOT NULL default '',
`articleinfophotowidth` varchar(250) NOT NULL default '',
`articleinfophotoheight` varchar(250) NOT NULL default '',
`addsorttype` varchar(250) NOT NULL default '',
`ordersorttype` varchar(250) NOT NULL default '',
`timesorttype` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}feedback" => "CREATE TABLE `{$mydbpre}feedback` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`guestname` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`fax` varchar(250) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`mobile` varchar(250) NOT NULL default '',
`qq` varchar(250) NOT NULL default '',
`msn` varchar(250) NOT NULL default '',
`company` varchar(250) NOT NULL default '',
`address` varchar(250) NOT NULL default '',
`ip` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}friendlink" => "CREATE TABLE `{$mydbpre}friendlink` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`alt` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}front" => "CREATE TABLE `{$mydbpre}front` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`content` mediumtext,
`url` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}guestbook" => "CREATE TABLE `{$mydbpre}guestbook` (
`id` int(5) unsigned NOT NULL auto_increment,
`guestname` varchar(250) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`qq` varchar(250) NOT NULL default '',
`msn` varchar(250) NOT NULL default '',
`face` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`address` varchar(250) NOT NULL default '',
`ip` varchar(250) NOT NULL default '',
`reply` varchar(250) NOT NULL default '',
`fozu` varchar(250) NOT NULL default '',
`toname` varchar(250) NOT NULL default '',
`tomail` varchar(250) NOT NULL default '',
`tophone` varchar(250) NOT NULL default '',
`myname` varchar(250) NOT NULL default '',
`mymail` varchar(250) NOT NULL default '',
`myphone` varchar(250) NOT NULL default '',
`mycontent` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}inputconfig" => "CREATE TABLE `{$mydbpre}inputconfig` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`fronttitle` varchar(250) NOT NULL default '',
`backendtitle` varchar(250) NOT NULL default '',
`fieldname` varchar(250) NOT NULL default '',
`customfieldname` varchar(250) NOT NULL default '',
`inputtype` varchar(250) NOT NULL default '',
`inputwidth` varchar(250) NOT NULL default '',
`inputheight` varchar(250) NOT NULL default '',
`verificationtype` varchar(250) NOT NULL default '',
`verificationmsg` varchar(250) NOT NULL default '',
`tipstext` varchar(250) NOT NULL default '',
`defaultvalue` varchar(250) NOT NULL default '',
`placeholder` varchar(250) NOT NULL default '',
`listshow` varchar(250) NOT NULL default '',
`editdialogshow` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}inputvalue" => "CREATE TABLE `{$mydbpre}inputvalue` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`str1` varchar(250) NOT NULL default '',
`str2` varchar(250) NOT NULL default '',
`str3` varchar(250) NOT NULL default '',
`str4` varchar(250) NOT NULL default '',
`str5` varchar(250) NOT NULL default '',
`str6` varchar(250) NOT NULL default '',
`str7` varchar(250) NOT NULL default '',
`str8` varchar(250) NOT NULL default '',
`str9` varchar(250) NOT NULL default '',
`str10` varchar(250) NOT NULL default '',
`str11` varchar(250) NOT NULL default '',
`str12` varchar(250) NOT NULL default '',
`str13` varchar(250) NOT NULL default '',
`str14` varchar(250) NOT NULL default '',
`str15` varchar(250) NOT NULL default '',
`numb1` varchar(250) NOT NULL default '',
`numb2` varchar(250) NOT NULL default '',
`numb3` varchar(250) NOT NULL default '',
`numb4` varchar(250) NOT NULL default '',
`numb5` varchar(250) NOT NULL default '',
`numb6` varchar(250) NOT NULL default '',
`numb7` varchar(250) NOT NULL default '',
`numb8` varchar(250) NOT NULL default '',
`numb9` varchar(250) NOT NULL default '',
`truefalse1` varchar(250) NOT NULL default '',
`truefalse2` varchar(250) NOT NULL default '',
`truefalse3` varchar(250) NOT NULL default '',
`truefalse4` varchar(250) NOT NULL default '',
`truefalse5` varchar(250) NOT NULL default '',
`truefalse6` varchar(250) NOT NULL default '',
`truefalse7` varchar(250) NOT NULL default '',
`truefalse8` varchar(250) NOT NULL default '',
`truefalse9` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}job" => "CREATE TABLE `{$mydbpre}job` (
`id` int(5) unsigned NOT NULL auto_increment,
`sex` varchar(250) NOT NULL default '',
`age` varchar(250) NOT NULL default '',
`education` varchar(250) NOT NULL default '',
`workarea` varchar(250) NOT NULL default '',
`post` varchar(250) NOT NULL default '',
`monthly` varchar(250) NOT NULL default '',
`startdatetime` varchar(250) NOT NULL default '',
`enddatetime` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}listmenu" => "CREATE TABLE `{$mydbpre}listmenu` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`smallclassname` varchar(250) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}maininfo" => "CREATE TABLE `{$mydbpre}maininfo` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`showtitle` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`recommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`helptext` varchar(250) NOT NULL default '',
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}member" => "CREATE TABLE `{$mydbpre}member` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`username` varchar(250) NOT NULL default '',
`pwd` varchar(250) NOT NULL default '',
`yunpwd` varchar(250) NOT NULL default '',
`sex` varchar(250) NOT NULL default '',
`age` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`phone` varchar(250) NOT NULL default '',
`fax` varchar(250) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`zipcode` varchar(250) NOT NULL default '',
`address` varchar(250) NOT NULL default '',
`company` varchar(250) NOT NULL default '',
`regip` varchar(250) NOT NULL default '',
`logip` varchar(250) NOT NULL default '',
`loginnumb` varchar(250) NOT NULL default '',
`logintime` varchar(250) NOT NULL default '',
`lastlogintime` varchar(250) NOT NULL default '',
`scene` varchar(250) NOT NULL default '',
`scenemap` varchar(250) NOT NULL default '',
`renjb` varchar(250) NOT NULL default '',
`fobi` varchar(250) NOT NULL default '',
`myname` varchar(250) NOT NULL default '',
`mymoney` varchar(250) NOT NULL default '',
`deposit` varchar(250) NOT NULL default '',
`renhp` varchar(250) NOT NULL default '',
`renmp` varchar(250) NOT NULL default '',
`renexp` varchar(250) NOT NULL default '',
`wbchouti` varchar(250) NOT NULL default '',
`thex` varchar(250) NOT NULL default '',
`they` varchar(250) NOT NULL default '',
`openid` varchar(250) NOT NULL default '',
`access_token` varchar(250) NOT NULL default '',
`qqphoto` varchar(250) NOT NULL default '',
`province` varchar(250) NOT NULL default '',
`city` varchar(250) NOT NULL default '',
`area` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`content` mediumtext,
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}navbigclass" => "CREATE TABLE `{$mydbpre}navbigclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`navenglish` varchar(250) NOT NULL default '',
`navurl` varchar(250) NOT NULL default '',
`navtype` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`navtop` varchar(250) NOT NULL default '',
`navbuttom` varchar(250) NOT NULL default '',
`navleft` varchar(250) NOT NULL default '',
`navcontent` varchar(250) NOT NULL default '',
`navright` varchar(250) NOT NULL default '',
`navothre` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}navsmallclass" => "CREATE TABLE `{$mydbpre}navsmallclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`smallclassname` varchar(250) NOT NULL default '',
`navurl` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`navtitle` varchar(250) NOT NULL default '',
`navkeywords` varchar(250) NOT NULL default '',
`navdescription` varchar(250) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}onepage" => "CREATE TABLE `{$mydbpre}onepage` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`displaytitle` varchar(250) NOT NULL default '',
`adminid` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`isrecommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`helptext` varchar(250) NOT NULL default '',
`customaurl` varchar(250) NOT NULL default '',
`noteinfo` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}onlineqq" => "CREATE TABLE `{$mydbpre}onlineqq` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`qq` varchar(250) NOT NULL default '',
`isonlinechat` varchar(250) NOT NULL default '',
`isaddfriend` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}payment" => "CREATE TABLE `{$mydbpre}payment` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(250) NOT NULL default '',
`memberid` varchar(250) NOT NULL default '',
`sex` varchar(250) NOT NULL default '',
`age` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`phone` varchar(250) NOT NULL default '',
`fax` varchar(250) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`zipcode` varchar(250) NOT NULL default '',
`address` varchar(250) NOT NULL default '',
`company` varchar(250) NOT NULL default '',
`qqmsn` varchar(250) NOT NULL default '',
`ip` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}previeworder" => "CREATE TABLE `{$mydbpre}previeworder` (
`id` int(5) unsigned NOT NULL auto_increment,
`memberid` varchar(250) NOT NULL default '',
`orderid` varchar(250) NOT NULL default '',
`productid` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`total` varchar(250) NOT NULL default '',
`price` varchar(250) NOT NULL default '',
`productsum` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}product" => "CREATE TABLE `{$mydbpre}product` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`smallclassname` varchar(250) NOT NULL default '',
`threeclassname` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`recommend` varchar(250) NOT NULL default '',
`homerecommend` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`hot` varchar(250) NOT NULL default '',
`occasions` varchar(250) NOT NULL default '',
`hotline` varchar(250) NOT NULL default '',
`model` varchar(250) NOT NULL default '',
`author` varchar(250) NOT NULL default '',
`articlesource` varchar(250) NOT NULL default '',
`price` varchar(250) NOT NULL default '',
`newprice` varchar(250) NOT NULL default '',
`memberprice` varchar(250) NOT NULL default '',
`sold` varchar(250) NOT NULL default '',
`membertype` varchar(250) NOT NULL default '',
`memberuser` varchar(250) NOT NULL default '',
`hits` varchar(250) NOT NULL default '',
`bigfiles` varchar(250) NOT NULL default '',
`smallfiles` varchar(250) NOT NULL default '',
`titlealt` varchar(250) NOT NULL default '',
`bigfilesalt` varchar(250) NOT NULL default '',
`smallfilesalt` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`productabout` varchar(250) NOT NULL default '',
`articledescription` varchar(250) NOT NULL default '',
`httpurl` varchar(250) NOT NULL default '',
`recordurl` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`ncount` varchar(250) NOT NULL default '',
`x` varchar(250) NOT NULL default '',
`y` varchar(250) NOT NULL default '',
`infoid` varchar(250) NOT NULL default '',
`wbchouti` varchar(250) NOT NULL default '',
`expiretime` varchar(250) NOT NULL default '',
`jinxinname` varchar(250) NOT NULL default '',
`articleinfostyle` varchar(250) NOT NULL default '',
`articleinfophotowidth` varchar(250) NOT NULL default '',
`articleinfophotoheight` varchar(250) NOT NULL default '',
`relatedtags` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}productcomment" => "CREATE TABLE `{$mydbpre}productcomment` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`pid` varchar(250) NOT NULL default '',
`ptitle` varchar(250) NOT NULL default '',
`content` mediumtext,
`sort` varchar(250) NOT NULL default '',
`ip` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}productparameter" => "CREATE TABLE `{$mydbpre}productparameter` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`pttitle` varchar(250) NOT NULL default '',
`ptstart` varchar(250) NOT NULL default '',
`ptend` varchar(250) NOT NULL default '',
`pid` varchar(250) NOT NULL default '',
`homerecommend` varchar(250) NOT NULL default '',
`inforecommend` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`ptvalue1` varchar(250) NOT NULL default '',
`ptvalue2` varchar(250) NOT NULL default '',
`ptvalue3` varchar(250) NOT NULL default '',
`ptvalue4` varchar(250) NOT NULL default '',
`ptvalue5` varchar(250) NOT NULL default '',
`ptvalue6` varchar(250) NOT NULL default '',
`ptvalue7` varchar(250) NOT NULL default '',
`ptvalue8` varchar(250) NOT NULL default '',
`ptvalue9` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}qqmsn" => "CREATE TABLE `{$mydbpre}qqmsn` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`website` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`qqnumber` varchar(250) NOT NULL default '',
`qqname` varchar(250) NOT NULL default '',
`msnnumber` varchar(250) NOT NULL default '',
`msnname` varchar(250) NOT NULL default '',
`qqstyle` varchar(250) NOT NULL default '',
`qqpicture` varchar(250) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}searchcount" => "CREATE TABLE `{$mydbpre}searchcount` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}smallclass" => "CREATE TABLE `{$mydbpre}smallclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`smallclassname` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`uploadfiles` varchar(250) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(250) NOT NULL default '',
`articlepagesize` varchar(250) NOT NULL default '',
`articleinfostyle` varchar(250) NOT NULL default '',
`articleinfophotowidth` varchar(250) NOT NULL default '',
`articleinfophotoheight` varchar(250) NOT NULL default '',
`addsorttype` varchar(250) NOT NULL default '',
`ordersorttype` varchar(250) NOT NULL default '',
`timesorttype` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}softtask" => "CREATE TABLE `{$mydbpre}softtask` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`content` mediumtext,
`filepath` varchar(250) NOT NULL default '',
`nsort` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}tablecomment" => "CREATE TABLE `{$mydbpre}tablecomment` (
`id` int(5) unsigned NOT NULL auto_increment,
`userid` varchar(250) NOT NULL default '',
`itemid` varchar(250) NOT NULL default '',
`parentid` varchar(250) NOT NULL default '',
`tablename` varchar(250) NOT NULL default '',
`username` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`reply` varchar(250) NOT NULL default '',
`noteinfo` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}templatemodule" => "CREATE TABLE `{$mydbpre}templatemodule` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`showtitle` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`recommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`helpmsg` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}threeclass" => "CREATE TABLE `{$mydbpre}threeclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`smallclassname` varchar(250) NOT NULL default '',
`threeclassname` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(250) NOT NULL default '',
`articlepagesize` varchar(250) NOT NULL default '',
`articleinfostyle` varchar(250) NOT NULL default '',
`articleinfophotowidth` varchar(250) NOT NULL default '',
`articleinfophotoheight` varchar(250) NOT NULL default '',
`addsorttype` varchar(250) NOT NULL default '',
`ordersorttype` varchar(250) NOT NULL default '',
`timesorttype` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}vote" => "CREATE TABLE `{$mydbpre}vote` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`option1` varchar(250) NOT NULL default '',
`option2` varchar(250) NOT NULL default '',
`option3` varchar(250) NOT NULL default '',
`option4` varchar(250) NOT NULL default '',
`option5` varchar(250) NOT NULL default '',
`option6` varchar(250) NOT NULL default '',
`num1` varchar(250) NOT NULL default '',
`num2` varchar(250) NOT NULL default '',
`num3` varchar(250) NOT NULL default '',
`num4` varchar(250) NOT NULL default '',
`num5` varchar(250) NOT NULL default '',
`num6` varchar(250) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`votetype` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}watermark" => "CREATE TABLE `{$mydbpre}watermark` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`watermarktext` varchar(250) NOT NULL default '',
`watermarktextposition` varchar(250) NOT NULL default '',
`textx` varchar(250) NOT NULL default '',
`texty` varchar(250) NOT NULL default '',
`ntextsize` varchar(250) NOT NULL default '',
`textrotation` varchar(250) NOT NULL default '',
`textcolor` varchar(250) NOT NULL default '',
`watermarktypeface` varchar(250) NOT NULL default '',
`watermarkimgpath` varchar(250) NOT NULL default '',
`watermarkimgposition` varchar(250) NOT NULL default '',
`imgx` varchar(250) NOT NULL default '',
`imgy` varchar(250) NOT NULL default '',
`watermarkimgtransparency` varchar(250) NOT NULL default '',
`zoomwidth` varchar(250) NOT NULL default '',
`zoomheight` varchar(250) NOT NULL default '',
`nsort` varchar(250) NOT NULL default '',
`content` mediumtext,
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}webcolumn" => "CREATE TABLE `{$mydbpre}webcolumn` (
`id` int(5) unsigned NOT NULL auto_increment,
`columnname` varchar(250) NOT NULL default '',
`columnenname` varchar(250) NOT NULL default '',
`columntype` varchar(250) NOT NULL default '',
`parentid` varchar(250) NOT NULL default '',
`topid` varchar(250) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` varchar(250) NOT NULL default '',
`isdisplay` varchar(250) NOT NULL default '',
`smallimage` varchar(250) NOT NULL default '',
`bigimage` varchar(250) NOT NULL default '',
`bannerimage` varchar(250) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`showtitle` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`ismakehtml` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`npagesize` varchar(250) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`noteinfo` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}weblayout" => "CREATE TABLE `{$mydbpre}weblayout` (
`id` int(5) unsigned NOT NULL auto_increment,
`layoutname` varchar(250) NOT NULL default '',
`layoutlist` varchar(250) NOT NULL default '',
`replacestyle` varchar(250) NOT NULL default '',
`actioncontent` varchar(250) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`isdisplay` varchar(250) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}weblink" => "CREATE TABLE `{$mydbpre}weblink` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`content` mediumtext,
`sort` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}webmodule" => "CREATE TABLE `{$mydbpre}webmodule` (
`id` int(5) unsigned NOT NULL auto_increment,
`moduletype` mediumtext,
`modulename` mediumtext,
`title` varchar(255) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`isdisplay` varchar(250) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}website" => "CREATE TABLE `{$mydbpre}website` (
`id` int(5) unsigned NOT NULL auto_increment,
`websiteurl` varchar(250) NOT NULL default '',
`websitebottom` varchar(250) NOT NULL default '',
`websiteflow` varchar(250) NOT NULL default '',
`websiteflowstyle` varchar(250) NOT NULL default '',
`websiteflowmedian` varchar(250) NOT NULL default '',
`productlist` varchar(250) NOT NULL default '',
`newslist` varchar(250) NOT NULL default '',
`newsdid` varchar(250) NOT NULL default '',
`tz51la` varchar(250) NOT NULL default '',
`useremail` varchar(250) NOT NULL default '',
`productdid` varchar(250) NOT NULL default '',
`templateindex` varchar(250) NOT NULL default '',
`templatehome` varchar(250) NOT NULL default '',
`templatemain` varchar(250) NOT NULL default '',
`templatemain2` varchar(250) NOT NULL default '',
`templatemain3` varchar(250) NOT NULL default '',
`usenumb` varchar(250) NOT NULL default '',
`webrecord` varchar(250) NOT NULL default '',
`contentwebrecord` varchar(250) NOT NULL default '',
`usehttpurl` varchar(250) NOT NULL default '',
`tempusehttpurl` varchar(250) NOT NULL default '',
`webdate` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`webtemplate` varchar(250) NOT NULL default '',
`webskins` varchar(250) NOT NULL default '',
`webfoldername` varchar(250) NOT NULL default '',
`webimages` varchar(250) NOT NULL default '',
`webcss` varchar(250) NOT NULL default '',
`webjs` varchar(250) NOT NULL default '',
`addwebsite` varchar(250) NOT NULL default '',
`updatehtml` varchar(250) NOT NULL default '',
`ishtmlformatting` varchar(250) NOT NULL default '',
`isweblabelclose` varchar(250) NOT NULL default '',
`iscntoen` varchar(250) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`moduleskins` mediumtext,
`findtpl` varchar(250) NOT NULL default '',
`replacetpl` varchar(250) NOT NULL default '',
`webcodefindtpl` varchar(250) NOT NULL default '',
`webcodereplacetpl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`webhtml` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}websitestat" => "CREATE TABLE `{$mydbpre}websitestat` (
`id` int(5) unsigned NOT NULL auto_increment,
`visiturl` varchar(255) NOT NULL default '',
`viewurl` varchar(255) NOT NULL default '',
`browser` varchar(255) NOT NULL default '',
`operatingsystem` varchar(250) NOT NULL default '',
`screenwh` varchar(250) NOT NULL default '',
`moreinfo` varchar(250) NOT NULL default '',
`viewdatetime` varchar(250) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`dateclass` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`noteinfo` varchar(250) NOT NULL default '',
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}webtemplate" => "CREATE TABLE `{$mydbpre}webtemplate` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`bigclassname` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`mbparameter` varchar(250) NOT NULL default '',
`recommend` varchar(250) NOT NULL default '',
`mbupdate` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_admin" => "CREATE TABLE `{$mydbpre}xy_admin` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(250) NOT NULL default '',
`pwd` varchar(250) NOT NULL default '',
`pseudonym` varchar(255) NOT NULL default '',
`adminlevel` varchar(250) NOT NULL default '',
`channel` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`regip` varchar(250) NOT NULL default '',
`upip` varchar(250) NOT NULL default '',
`quanxian` varchar(250) NOT NULL default '',
`verificationmode` varchar(250) NOT NULL default '',
`mtest` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_articledetail" => "CREATE TABLE `{$mydbpre}xy_articledetail` (
`id` int(5) unsigned NOT NULL auto_increment,
`parentid` varchar(250) NOT NULL default '',
`topid` varchar(250) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` varchar(250) NOT NULL default '',
`smallimage` varchar(250) NOT NULL default '',
`bigimage` varchar(250) NOT NULL default '',
`bannerimage` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`titlecolor` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`ischeck` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`occasions` varchar(250) NOT NULL default '',
`hotline` varchar(250) NOT NULL default '',
`model` varchar(250) NOT NULL default '',
`author` varchar(250) NOT NULL default '',
`articlesource` varchar(250) NOT NULL default '',
`price` varchar(250) NOT NULL default '',
`newprice` varchar(250) NOT NULL default '',
`memberprice` varchar(250) NOT NULL default '',
`sold` varchar(250) NOT NULL default '',
`membertype` varchar(250) NOT NULL default '',
`memberuser` varchar(250) NOT NULL default '',
`hits` varchar(250) NOT NULL default '',
`titlealt` varchar(250) NOT NULL default '',
`bigfilesalt` varchar(250) NOT NULL default '',
`smallfilesalt` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`productabout` varchar(250) NOT NULL default '',
`articledescription` varchar(250) NOT NULL default '',
`httpurl` varchar(250) NOT NULL default '',
`recordurl` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`ncount` varchar(250) NOT NULL default '',
`articleinfostyle` varchar(250) NOT NULL default '',
`articleinfophotowidth` varchar(250) NOT NULL default '',
`articleinfophotoheight` varchar(250) NOT NULL default '',
`relatedtags` varchar(250) NOT NULL default '',
`weight` int(8) NOT NULL default '0',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`noteinfo` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_bidding" => "CREATE TABLE `{$mydbpre}xy_bidding` (
`id` int(5) unsigned NOT NULL auto_increment,
`searchwords` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`showreason` varchar(250) NOT NULL default '',
`ncomputersearch` varchar(250) NOT NULL default '',
`nmobliesearch` varchar(250) NOT NULL default '',
`ncountsearch` varchar(250) NOT NULL default '',
`nwordprice` varchar(250) NOT NULL default '',
`ndegree` varchar(250) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_bigclass" => "CREATE TABLE `{$mydbpre}xy_bigclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(250) NOT NULL default '',
`articlepagesize` varchar(250) NOT NULL default '',
`articleinfostyle` varchar(250) NOT NULL default '',
`articleinfophotowidth` varchar(250) NOT NULL default '',
`articleinfophotoheight` varchar(250) NOT NULL default '',
`addsorttype` varchar(250) NOT NULL default '',
`ordersorttype` varchar(250) NOT NULL default '',
`timesorttype` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_feedback" => "CREATE TABLE `{$mydbpre}xy_feedback` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`guestname` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`fax` varchar(250) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`mobile` varchar(250) NOT NULL default '',
`qq` varchar(250) NOT NULL default '',
`msn` varchar(250) NOT NULL default '',
`company` varchar(250) NOT NULL default '',
`address` varchar(250) NOT NULL default '',
`ip` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_friendlink" => "CREATE TABLE `{$mydbpre}xy_friendlink` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`alt` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_front" => "CREATE TABLE `{$mydbpre}xy_front` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`content` mediumtext,
`url` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_guestbook" => "CREATE TABLE `{$mydbpre}xy_guestbook` (
`id` int(5) unsigned NOT NULL auto_increment,
`guestname` varchar(250) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`qq` varchar(250) NOT NULL default '',
`msn` varchar(250) NOT NULL default '',
`face` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`address` varchar(250) NOT NULL default '',
`ip` varchar(250) NOT NULL default '',
`reply` varchar(250) NOT NULL default '',
`fozu` varchar(250) NOT NULL default '',
`toname` varchar(250) NOT NULL default '',
`tomail` varchar(250) NOT NULL default '',
`tophone` varchar(250) NOT NULL default '',
`myname` varchar(250) NOT NULL default '',
`mymail` varchar(250) NOT NULL default '',
`myphone` varchar(250) NOT NULL default '',
`mycontent` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_inputconfig" => "CREATE TABLE `{$mydbpre}xy_inputconfig` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`fronttitle` varchar(250) NOT NULL default '',
`backendtitle` varchar(250) NOT NULL default '',
`fieldname` varchar(250) NOT NULL default '',
`customfieldname` varchar(250) NOT NULL default '',
`inputtype` varchar(250) NOT NULL default '',
`inputwidth` varchar(250) NOT NULL default '',
`inputheight` varchar(250) NOT NULL default '',
`verificationtype` varchar(250) NOT NULL default '',
`verificationmsg` varchar(250) NOT NULL default '',
`tipstext` varchar(250) NOT NULL default '',
`defaultvalue` varchar(250) NOT NULL default '',
`placeholder` varchar(250) NOT NULL default '',
`listshow` varchar(250) NOT NULL default '',
`editdialogshow` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_inputvalue" => "CREATE TABLE `{$mydbpre}xy_inputvalue` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`str1` varchar(250) NOT NULL default '',
`str2` varchar(250) NOT NULL default '',
`str3` varchar(250) NOT NULL default '',
`str4` varchar(250) NOT NULL default '',
`str5` varchar(250) NOT NULL default '',
`str6` varchar(250) NOT NULL default '',
`str7` varchar(250) NOT NULL default '',
`str8` varchar(250) NOT NULL default '',
`str9` varchar(250) NOT NULL default '',
`str10` varchar(250) NOT NULL default '',
`str11` varchar(250) NOT NULL default '',
`str12` varchar(250) NOT NULL default '',
`str13` varchar(250) NOT NULL default '',
`str14` varchar(250) NOT NULL default '',
`str15` varchar(250) NOT NULL default '',
`numb1` varchar(250) NOT NULL default '',
`numb2` varchar(250) NOT NULL default '',
`numb3` varchar(250) NOT NULL default '',
`numb4` varchar(250) NOT NULL default '',
`numb5` varchar(250) NOT NULL default '',
`numb6` varchar(250) NOT NULL default '',
`numb7` varchar(250) NOT NULL default '',
`numb8` varchar(250) NOT NULL default '',
`numb9` varchar(250) NOT NULL default '',
`truefalse1` varchar(250) NOT NULL default '',
`truefalse2` varchar(250) NOT NULL default '',
`truefalse3` varchar(250) NOT NULL default '',
`truefalse4` varchar(250) NOT NULL default '',
`truefalse5` varchar(250) NOT NULL default '',
`truefalse6` varchar(250) NOT NULL default '',
`truefalse7` varchar(250) NOT NULL default '',
`truefalse8` varchar(250) NOT NULL default '',
`truefalse9` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_job" => "CREATE TABLE `{$mydbpre}xy_job` (
`id` int(5) unsigned NOT NULL auto_increment,
`sex` varchar(250) NOT NULL default '',
`age` varchar(250) NOT NULL default '',
`education` varchar(250) NOT NULL default '',
`workarea` varchar(250) NOT NULL default '',
`post` varchar(250) NOT NULL default '',
`monthly` varchar(250) NOT NULL default '',
`startdatetime` varchar(250) NOT NULL default '',
`enddatetime` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_listmenu" => "CREATE TABLE `{$mydbpre}xy_listmenu` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`smallclassname` varchar(250) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_maininfo" => "CREATE TABLE `{$mydbpre}xy_maininfo` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`showtitle` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`recommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`helptext` varchar(250) NOT NULL default '',
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_member" => "CREATE TABLE `{$mydbpre}xy_member` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`username` varchar(250) NOT NULL default '',
`pwd` varchar(250) NOT NULL default '',
`yunpwd` varchar(250) NOT NULL default '',
`sex` varchar(250) NOT NULL default '',
`age` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`phone` varchar(250) NOT NULL default '',
`fax` varchar(250) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`zipcode` varchar(250) NOT NULL default '',
`address` varchar(250) NOT NULL default '',
`company` varchar(250) NOT NULL default '',
`regip` varchar(250) NOT NULL default '',
`logip` varchar(250) NOT NULL default '',
`loginnumb` varchar(250) NOT NULL default '',
`logintime` varchar(250) NOT NULL default '',
`lastlogintime` varchar(250) NOT NULL default '',
`scene` varchar(250) NOT NULL default '',
`scenemap` varchar(250) NOT NULL default '',
`renjb` varchar(250) NOT NULL default '',
`fobi` varchar(250) NOT NULL default '',
`myname` varchar(250) NOT NULL default '',
`mymoney` varchar(250) NOT NULL default '',
`deposit` varchar(250) NOT NULL default '',
`renhp` varchar(250) NOT NULL default '',
`renmp` varchar(250) NOT NULL default '',
`renexp` varchar(250) NOT NULL default '',
`wbchouti` varchar(250) NOT NULL default '',
`thex` varchar(250) NOT NULL default '',
`they` varchar(250) NOT NULL default '',
`openid` varchar(250) NOT NULL default '',
`access_token` varchar(250) NOT NULL default '',
`qqphoto` varchar(250) NOT NULL default '',
`province` varchar(250) NOT NULL default '',
`city` varchar(250) NOT NULL default '',
`area` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`content` mediumtext,
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_navbigclass" => "CREATE TABLE `{$mydbpre}xy_navbigclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`navenglish` varchar(250) NOT NULL default '',
`navurl` varchar(250) NOT NULL default '',
`navtype` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`navtop` varchar(250) NOT NULL default '',
`navbuttom` varchar(250) NOT NULL default '',
`navleft` varchar(250) NOT NULL default '',
`navcontent` varchar(250) NOT NULL default '',
`navright` varchar(250) NOT NULL default '',
`navothre` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_navsmallclass" => "CREATE TABLE `{$mydbpre}xy_navsmallclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`smallclassname` varchar(250) NOT NULL default '',
`navurl` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`navtitle` varchar(250) NOT NULL default '',
`navkeywords` varchar(250) NOT NULL default '',
`navdescription` varchar(250) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_onepage" => "CREATE TABLE `{$mydbpre}xy_onepage` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`displaytitle` varchar(250) NOT NULL default '',
`adminid` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`isrecommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`helptext` varchar(250) NOT NULL default '',
`customaurl` varchar(250) NOT NULL default '',
`noteinfo` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_onlineqq" => "CREATE TABLE `{$mydbpre}xy_onlineqq` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`qq` varchar(250) NOT NULL default '',
`isonlinechat` varchar(250) NOT NULL default '',
`isaddfriend` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_payment" => "CREATE TABLE `{$mydbpre}xy_payment` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(250) NOT NULL default '',
`memberid` varchar(250) NOT NULL default '',
`sex` varchar(250) NOT NULL default '',
`age` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`phone` varchar(250) NOT NULL default '',
`fax` varchar(250) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`zipcode` varchar(250) NOT NULL default '',
`address` varchar(250) NOT NULL default '',
`company` varchar(250) NOT NULL default '',
`qqmsn` varchar(250) NOT NULL default '',
`ip` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_previeworder" => "CREATE TABLE `{$mydbpre}xy_previeworder` (
`id` int(5) unsigned NOT NULL auto_increment,
`memberid` varchar(250) NOT NULL default '',
`orderid` varchar(250) NOT NULL default '',
`productid` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`total` varchar(250) NOT NULL default '',
`price` varchar(250) NOT NULL default '',
`productsum` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_product" => "CREATE TABLE `{$mydbpre}xy_product` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`smallclassname` varchar(250) NOT NULL default '',
`threeclassname` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`recommend` varchar(250) NOT NULL default '',
`homerecommend` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`hot` varchar(250) NOT NULL default '',
`occasions` varchar(250) NOT NULL default '',
`hotline` varchar(250) NOT NULL default '',
`model` varchar(250) NOT NULL default '',
`author` varchar(250) NOT NULL default '',
`articlesource` varchar(250) NOT NULL default '',
`price` varchar(250) NOT NULL default '',
`newprice` varchar(250) NOT NULL default '',
`memberprice` varchar(250) NOT NULL default '',
`sold` varchar(250) NOT NULL default '',
`membertype` varchar(250) NOT NULL default '',
`memberuser` varchar(250) NOT NULL default '',
`hits` varchar(250) NOT NULL default '',
`bigfiles` varchar(250) NOT NULL default '',
`smallfiles` varchar(250) NOT NULL default '',
`titlealt` varchar(250) NOT NULL default '',
`bigfilesalt` varchar(250) NOT NULL default '',
`smallfilesalt` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`productabout` varchar(250) NOT NULL default '',
`articledescription` varchar(250) NOT NULL default '',
`httpurl` varchar(250) NOT NULL default '',
`recordurl` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`ncount` varchar(250) NOT NULL default '',
`x` varchar(250) NOT NULL default '',
`y` varchar(250) NOT NULL default '',
`infoid` varchar(250) NOT NULL default '',
`wbchouti` varchar(250) NOT NULL default '',
`expiretime` varchar(250) NOT NULL default '',
`jinxinname` varchar(250) NOT NULL default '',
`articleinfostyle` varchar(250) NOT NULL default '',
`articleinfophotowidth` varchar(250) NOT NULL default '',
`articleinfophotoheight` varchar(250) NOT NULL default '',
`relatedtags` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_productcomment" => "CREATE TABLE `{$mydbpre}xy_productcomment` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`pid` varchar(250) NOT NULL default '',
`ptitle` varchar(250) NOT NULL default '',
`content` mediumtext,
`sort` varchar(250) NOT NULL default '',
`ip` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_productparameter" => "CREATE TABLE `{$mydbpre}xy_productparameter` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`pttitle` varchar(250) NOT NULL default '',
`ptstart` varchar(250) NOT NULL default '',
`ptend` varchar(250) NOT NULL default '',
`pid` varchar(250) NOT NULL default '',
`homerecommend` varchar(250) NOT NULL default '',
`inforecommend` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`ptvalue1` varchar(250) NOT NULL default '',
`ptvalue2` varchar(250) NOT NULL default '',
`ptvalue3` varchar(250) NOT NULL default '',
`ptvalue4` varchar(250) NOT NULL default '',
`ptvalue5` varchar(250) NOT NULL default '',
`ptvalue6` varchar(250) NOT NULL default '',
`ptvalue7` varchar(250) NOT NULL default '',
`ptvalue8` varchar(250) NOT NULL default '',
`ptvalue9` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_qqmsn" => "CREATE TABLE `{$mydbpre}xy_qqmsn` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`website` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`qqnumber` varchar(250) NOT NULL default '',
`qqname` varchar(250) NOT NULL default '',
`msnnumber` varchar(250) NOT NULL default '',
`msnname` varchar(250) NOT NULL default '',
`qqstyle` varchar(250) NOT NULL default '',
`qqpicture` varchar(250) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_searchcount" => "CREATE TABLE `{$mydbpre}xy_searchcount` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_smallclass" => "CREATE TABLE `{$mydbpre}xy_smallclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`smallclassname` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`uploadfiles` varchar(250) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(250) NOT NULL default '',
`articlepagesize` varchar(250) NOT NULL default '',
`articleinfostyle` varchar(250) NOT NULL default '',
`articleinfophotowidth` varchar(250) NOT NULL default '',
`articleinfophotoheight` varchar(250) NOT NULL default '',
`addsorttype` varchar(250) NOT NULL default '',
`ordersorttype` varchar(250) NOT NULL default '',
`timesorttype` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_softtask" => "CREATE TABLE `{$mydbpre}xy_softtask` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`content` mediumtext,
`filepath` varchar(250) NOT NULL default '',
`nsort` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_tablecomment" => "CREATE TABLE `{$mydbpre}xy_tablecomment` (
`id` int(5) unsigned NOT NULL auto_increment,
`userid` varchar(250) NOT NULL default '',
`itemid` varchar(250) NOT NULL default '',
`parentid` varchar(250) NOT NULL default '',
`tablename` varchar(250) NOT NULL default '',
`username` varchar(250) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`email` varchar(250) NOT NULL default '',
`tel` varchar(250) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`reply` varchar(250) NOT NULL default '',
`noteinfo` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_templatemodule" => "CREATE TABLE `{$mydbpre}xy_templatemodule` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`showtitle` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`recommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`helpmsg` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_threeclass" => "CREATE TABLE `{$mydbpre}xy_threeclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(250) NOT NULL default '',
`smallclassname` varchar(250) NOT NULL default '',
`threeclassname` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(250) NOT NULL default '',
`articlepagesize` varchar(250) NOT NULL default '',
`articleinfostyle` varchar(250) NOT NULL default '',
`articleinfophotowidth` varchar(250) NOT NULL default '',
`articleinfophotoheight` varchar(250) NOT NULL default '',
`addsorttype` varchar(250) NOT NULL default '',
`ordersorttype` varchar(250) NOT NULL default '',
`timesorttype` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_vote" => "CREATE TABLE `{$mydbpre}xy_vote` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`option1` varchar(250) NOT NULL default '',
`option2` varchar(250) NOT NULL default '',
`option3` varchar(250) NOT NULL default '',
`option4` varchar(250) NOT NULL default '',
`option5` varchar(250) NOT NULL default '',
`option6` varchar(250) NOT NULL default '',
`num1` varchar(250) NOT NULL default '',
`num2` varchar(250) NOT NULL default '',
`num3` varchar(250) NOT NULL default '',
`num4` varchar(250) NOT NULL default '',
`num5` varchar(250) NOT NULL default '',
`num6` varchar(250) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`votetype` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_watermark" => "CREATE TABLE `{$mydbpre}xy_watermark` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`watermarktext` varchar(250) NOT NULL default '',
`watermarktextposition` varchar(250) NOT NULL default '',
`textx` varchar(250) NOT NULL default '',
`texty` varchar(250) NOT NULL default '',
`ntextsize` varchar(250) NOT NULL default '',
`textrotation` varchar(250) NOT NULL default '',
`textcolor` varchar(250) NOT NULL default '',
`watermarktypeface` varchar(250) NOT NULL default '',
`watermarkimgpath` varchar(250) NOT NULL default '',
`watermarkimgposition` varchar(250) NOT NULL default '',
`imgx` varchar(250) NOT NULL default '',
`imgy` varchar(250) NOT NULL default '',
`watermarkimgtransparency` varchar(250) NOT NULL default '',
`zoomwidth` varchar(250) NOT NULL default '',
`zoomheight` varchar(250) NOT NULL default '',
`nsort` varchar(250) NOT NULL default '',
`content` mediumtext,
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_webcolumn" => "CREATE TABLE `{$mydbpre}xy_webcolumn` (
`id` int(5) unsigned NOT NULL auto_increment,
`columnname` varchar(250) NOT NULL default '',
`columnenname` varchar(250) NOT NULL default '',
`columntype` varchar(250) NOT NULL default '',
`parentid` varchar(250) NOT NULL default '',
`topid` varchar(250) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` varchar(250) NOT NULL default '',
`isdisplay` varchar(250) NOT NULL default '',
`smallimage` varchar(250) NOT NULL default '',
`bigimage` varchar(250) NOT NULL default '',
`bannerimage` varchar(250) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`showtitle` varchar(250) NOT NULL default '',
`labletitle` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`foldername` varchar(250) NOT NULL default '',
`filename` varchar(250) NOT NULL default '',
`templatepath` varchar(250) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`fontcolor` varchar(250) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`ismakehtml` varchar(250) NOT NULL default '',
`topmodule` mediumtext,
`bottommodule` mediumtext,
`leftmodule` mediumtext,
`middlemodule` mediumtext,
`rightmodule` mediumtext,
`customaurl` varchar(250) NOT NULL default '',
`npagesize` varchar(250) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`noteinfo` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_weblayout" => "CREATE TABLE `{$mydbpre}xy_weblayout` (
`id` int(5) unsigned NOT NULL auto_increment,
`layoutname` varchar(250) NOT NULL default '',
`layoutlist` varchar(250) NOT NULL default '',
`replacestyle` varchar(250) NOT NULL default '',
`actioncontent` varchar(250) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`isdisplay` varchar(250) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_weblink" => "CREATE TABLE `{$mydbpre}xy_weblink` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`url` varchar(250) NOT NULL default '',
`imgpath` varchar(250) NOT NULL default '',
`content` mediumtext,
`sort` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_webmodule" => "CREATE TABLE `{$mydbpre}xy_webmodule` (
`id` int(5) unsigned NOT NULL auto_increment,
`moduletype` mediumtext,
`modulename` mediumtext,
`title` varchar(255) NOT NULL default '',
`sortrank` varchar(250) NOT NULL default '',
`isdisplay` varchar(250) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_website" => "CREATE TABLE `{$mydbpre}xy_website` (
`id` int(5) unsigned NOT NULL auto_increment,
`websiteurl` varchar(250) NOT NULL default '',
`websitebottom` varchar(250) NOT NULL default '',
`websiteflow` varchar(250) NOT NULL default '',
`websiteflowstyle` varchar(250) NOT NULL default '',
`websiteflowmedian` varchar(250) NOT NULL default '',
`productlist` varchar(250) NOT NULL default '',
`newslist` varchar(250) NOT NULL default '',
`newsdid` varchar(250) NOT NULL default '',
`tz51la` varchar(250) NOT NULL default '',
`useremail` varchar(250) NOT NULL default '',
`productdid` varchar(250) NOT NULL default '',
`templateindex` varchar(250) NOT NULL default '',
`templatehome` varchar(250) NOT NULL default '',
`templatemain` varchar(250) NOT NULL default '',
`templatemain2` varchar(250) NOT NULL default '',
`templatemain3` varchar(250) NOT NULL default '',
`usenumb` varchar(250) NOT NULL default '',
`webrecord` varchar(250) NOT NULL default '',
`contentwebrecord` varchar(250) NOT NULL default '',
`usehttpurl` varchar(250) NOT NULL default '',
`tempusehttpurl` varchar(250) NOT NULL default '',
`webdate` varchar(250) NOT NULL default '',
`webtitle` varchar(250) NOT NULL default '',
`webkeywords` varchar(250) NOT NULL default '',
`webdescription` varchar(250) NOT NULL default '',
`webtemplate` varchar(250) NOT NULL default '',
`webskins` varchar(250) NOT NULL default '',
`webfoldername` varchar(250) NOT NULL default '',
`webimages` varchar(250) NOT NULL default '',
`webcss` varchar(250) NOT NULL default '',
`webjs` varchar(250) NOT NULL default '',
`addwebsite` varchar(250) NOT NULL default '',
`updatehtml` varchar(250) NOT NULL default '',
`ishtmlformatting` varchar(250) NOT NULL default '',
`isweblabelclose` varchar(250) NOT NULL default '',
`iscntoen` varchar(250) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`moduleskins` mediumtext,
`findtpl` varchar(250) NOT NULL default '',
`replacetpl` varchar(250) NOT NULL default '',
`webcodefindtpl` varchar(250) NOT NULL default '',
`webcodereplacetpl` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`webhtml` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_websitestat" => "CREATE TABLE `{$mydbpre}xy_websitestat` (
`id` int(5) unsigned NOT NULL auto_increment,
`visiturl` varchar(255) NOT NULL default '',
`viewurl` varchar(255) NOT NULL default '',
`browser` varchar(255) NOT NULL default '',
`operatingsystem` varchar(250) NOT NULL default '',
`screenwh` varchar(250) NOT NULL default '',
`moreinfo` varchar(250) NOT NULL default '',
`viewdatetime` varchar(250) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`dateclass` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`noteinfo` varchar(250) NOT NULL default '',
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_webtemplate" => "CREATE TABLE `{$mydbpre}xy_webtemplate` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`bigclassname` varchar(250) NOT NULL default '',
`sort` varchar(250) NOT NULL default '',
`mbparameter` varchar(250) NOT NULL default '',
`recommend` varchar(250) NOT NULL default '',
`mbupdate` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
//access end

	);
	
	
	foreach ($sqlTables as $tableName => $tableSql){
		$conn->query("DROP TABLE IF EXISTS {$tableName}");					//为删除表
		$conn->query($tableSql);											//为创建表
		echo("创建数据表 {$tableName} 成功>><br>");
	}
	echo('<a href="/admin/index.php?act=setAccess">第三步，写入默认数据</a>');
	
    $conn->query('insert into admin (username,pwd) values(\'admin\',\'' . myMD5('admin') . '\')') ;
    $conn->query('insert into xy_admin (username,pwd) values(\'admin\',\'' . myMD5('admin') . '\')') ;
?>




































