<?php 
/************************************************************
作者：云端 (精通ASP/VB/PHP/JS/Flash，交流合作可联系本人)
版权：源代码公开，各种用途均可免费使用。 
创建：2016-02-29
联系：QQ313801120  交流群35915100(群里已有几百人)    邮箱313801120@qq.com   个人主页 sharembweb.com
更多帮助，文档，更新　请加群(35915100)或浏览(sharembweb.com)获得
*                                    Powered By AspPhpCMS 
************************************************************/
?>
<?php 
/************************************************************
作者：云端 (精通ASP/VB/PHP/JS/Flash，交流合作可联系本人)
版权：源代码公开，各种用途均可免费使用。 
创建：2016-02-29
联系：QQ313801120  交流群35915100(群里已有几百人)    邮箱313801120@qq.com   个人主页 sharembweb.com
更多帮助，文档，更新　请加群(35915100)或浏览(sharembweb.com)获得
*                                    Powered By AspPhpCMS 
************************************************************/
?>
<?PHP
require_once './ASP.php';
require_once './Conn.php';
require_once './MySqlClass.php';
//更新网址          http://127.0.0.1/phpAccess.asp
?>
<?PHP


 	$conn=OpenConn(); 
	$mydbcharset = 'gbk';				//编码
 	$mydbpre="";						//表前面的前缀
	$char = ' ENGINE=MyISAM DEFAULT CHARSET='.$mydbcharset;
	$sqlTables = array(
	
	//access start
"{$mydbpre}admin" => "CREATE TABLE `{$mydbpre}admin` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(255) NOT NULL default '',
`pwd` varchar(255) NOT NULL default '',
`pseudonym` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`regip` varchar(255) NOT NULL default '',
`upip` varchar(255) NOT NULL default '',
`quanxian` mediumtext,
`verificationmode` int(8) NOT NULL default '0',
`adminlevel` varchar(255) NOT NULL default '',
`channel` varchar(255) NOT NULL default '',
`mtest` varchar(250) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}articledetail" => "CREATE TABLE `{$mydbpre}articledetail` (
`id` int(5) unsigned NOT NULL auto_increment,
`parentid` int(8) NOT NULL default '0',
`topid` int(8) NOT NULL default '0',
`sortrank` int(8) NOT NULL default '0',
`views` int(8) NOT NULL default '0',
`adminid` int(8) NOT NULL default '0',
`smallimage` varchar(255) NOT NULL default '',
`bigimage` varchar(255) NOT NULL default '',
`bannerimage` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`titlecolor` varchar(255) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`ischeck` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`occasions` varchar(255) NOT NULL default '',
`hotline` varchar(255) NOT NULL default '',
`model` varchar(255) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`articlesource` varchar(255) NOT NULL default '',
`price` int(8) NOT NULL default '0',
`newprice` int(8) NOT NULL default '0',
`memberprice` int(8) NOT NULL default '0',
`sold` int(8) NOT NULL default '0',
`membertype` varchar(255) NOT NULL default '',
`memberuser` varchar(255) NOT NULL default '',
`hits` int(8) NOT NULL default '0',
`titlealt` varchar(255) NOT NULL default '',
`bigfilesalt` varchar(255) NOT NULL default '',
`smallfilesalt` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`productabout` mediumtext,
`articledescription` mediumtext,
`httpurl` varchar(255) NOT NULL default '',
`recordurl` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`flags` varchar(255) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`ncount` int(8) NOT NULL default '0',
`articleinfostyle` varchar(255) NOT NULL default '',
`articleinfophotowidth` varchar(255) NOT NULL default '',
`articleinfophotoheight` varchar(255) NOT NULL default '',
`relatedtags` varchar(255) NOT NULL default '',
`weight` int(8) NOT NULL default '0',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`noteinfo` mediumtext,
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}bidding" => "CREATE TABLE `{$mydbpre}bidding` (
`id` int(5) unsigned NOT NULL auto_increment,
`searchwords` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`showreason` varchar(255) NOT NULL default '',
`ncomputersearch` int(8) NOT NULL default '0',
`nmobliesearch` int(8) NOT NULL default '0',
`ncountsearch` int(8) NOT NULL default '0',
`nwordprice` int(8) NOT NULL default '0',
`ndegree` int(8) NOT NULL default '0',
`sortrank` int(8) NOT NULL default '0',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}bigclass" => "CREATE TABLE `{$mydbpre}bigclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(255) NOT NULL default '',
`articlepagesize` varchar(255) NOT NULL default '',
`articleinfostyle` varchar(255) NOT NULL default '',
`articleinfophotowidth` varchar(255) NOT NULL default '',
`articleinfophotoheight` varchar(255) NOT NULL default '',
`addsorttype` varchar(255) NOT NULL default '',
`ordersorttype` varchar(255) NOT NULL default '',
`timesorttype` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}feedback" => "CREATE TABLE `{$mydbpre}feedback` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`guestname` varchar(255) NOT NULL default '',
`tel` varchar(255) NOT NULL default '',
`fax` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`mobile` varchar(255) NOT NULL default '',
`qq` varchar(255) NOT NULL default '',
`msn` varchar(255) NOT NULL default '',
`company` varchar(255) NOT NULL default '',
`address` varchar(255) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}friendlink" => "CREATE TABLE `{$mydbpre}friendlink` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`alt` varchar(255) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}front" => "CREATE TABLE `{$mydbpre}front` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`content` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}guestbook" => "CREATE TABLE `{$mydbpre}guestbook` (
`id` int(5) unsigned NOT NULL auto_increment,
`guestname` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`tel` varchar(255) NOT NULL default '',
`qq` varchar(255) NOT NULL default '',
`msn` varchar(255) NOT NULL default '',
`face` int(8) NOT NULL default '0',
`through` varchar(250) NOT NULL default '',
`address` varchar(255) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`reply` mediumtext,
`fozu` varchar(255) NOT NULL default '',
`toname` varchar(255) NOT NULL default '',
`tomail` varchar(255) NOT NULL default '',
`tophone` varchar(255) NOT NULL default '',
`myname` varchar(255) NOT NULL default '',
`mymail` varchar(255) NOT NULL default '',
`myphone` varchar(255) NOT NULL default '',
`mycontent` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}inputconfig" => "CREATE TABLE `{$mydbpre}inputconfig` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`fronttitle` varchar(255) NOT NULL default '',
`backendtitle` varchar(255) NOT NULL default '',
`fieldname` varchar(255) NOT NULL default '',
`customfieldname` varchar(255) NOT NULL default '',
`inputtype` varchar(255) NOT NULL default '',
`inputwidth` varchar(255) NOT NULL default '',
`inputheight` varchar(255) NOT NULL default '',
`verificationtype` varchar(255) NOT NULL default '',
`verificationmsg` varchar(255) NOT NULL default '',
`tipstext` varchar(255) NOT NULL default '',
`defaultvalue` varchar(255) NOT NULL default '',
`placeholder` varchar(255) NOT NULL default '',
`listshow` varchar(250) NOT NULL default '',
`editdialogshow` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`through` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}inputvalue" => "CREATE TABLE `{$mydbpre}inputvalue` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`str1` varchar(255) NOT NULL default '',
`str2` varchar(255) NOT NULL default '',
`str3` varchar(255) NOT NULL default '',
`str4` varchar(255) NOT NULL default '',
`str5` varchar(255) NOT NULL default '',
`str6` varchar(255) NOT NULL default '',
`str7` varchar(255) NOT NULL default '',
`str8` varchar(255) NOT NULL default '',
`str9` varchar(255) NOT NULL default '',
`str10` varchar(255) NOT NULL default '',
`str11` varchar(255) NOT NULL default '',
`str12` varchar(255) NOT NULL default '',
`str13` varchar(255) NOT NULL default '',
`str14` varchar(255) NOT NULL default '',
`str15` varchar(255) NOT NULL default '',
`numb1` int(8) NOT NULL default '0',
`numb2` int(8) NOT NULL default '0',
`numb3` int(8) NOT NULL default '0',
`numb4` int(8) NOT NULL default '0',
`numb5` int(8) NOT NULL default '0',
`numb6` int(8) NOT NULL default '0',
`numb7` int(8) NOT NULL default '0',
`numb8` int(8) NOT NULL default '0',
`numb9` int(8) NOT NULL default '0',
`truefalse1` varchar(250) NOT NULL default '',
`truefalse2` varchar(250) NOT NULL default '',
`truefalse3` varchar(250) NOT NULL default '',
`truefalse4` varchar(250) NOT NULL default '',
`truefalse5` varchar(250) NOT NULL default '',
`truefalse6` varchar(250) NOT NULL default '',
`truefalse7` varchar(250) NOT NULL default '',
`truefalse8` varchar(250) NOT NULL default '',
`truefalse9` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`through` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}job" => "CREATE TABLE `{$mydbpre}job` (
`id` int(5) unsigned NOT NULL auto_increment,
`sex` varchar(255) NOT NULL default '',
`age` varchar(255) NOT NULL default '',
`education` varchar(255) NOT NULL default '',
`workarea` varchar(255) NOT NULL default '',
`post` varchar(255) NOT NULL default '',
`monthly` varchar(255) NOT NULL default '',
`startdatetime` varchar(255) NOT NULL default '',
`enddatetime` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}listmenu" => "CREATE TABLE `{$mydbpre}listmenu` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`smallclassname` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`display` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}maininfo" => "CREATE TABLE `{$mydbpre}maininfo` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`showtitle` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`recommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`helptext` mediumtext,
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}member" => "CREATE TABLE `{$mydbpre}member` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`username` varchar(255) NOT NULL default '',
`pwd` varchar(255) NOT NULL default '',
`yunpwd` varchar(255) NOT NULL default '',
`sex` varchar(255) NOT NULL default '',
`age` int(8) NOT NULL default '0',
`tel` varchar(255) NOT NULL default '',
`phone` varchar(255) NOT NULL default '',
`fax` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`zipcode` varchar(255) NOT NULL default '',
`address` varchar(255) NOT NULL default '',
`company` varchar(255) NOT NULL default '',
`regip` varchar(255) NOT NULL default '',
`logip` varchar(255) NOT NULL default '',
`loginnumb` int(8) NOT NULL default '0',
`logintime` varchar(250) NOT NULL default '',
`lastlogintime` varchar(250) NOT NULL default '',
`scene` varchar(255) NOT NULL default '',
`scenemap` varchar(255) NOT NULL default '',
`renjb` int(8) NOT NULL default '0',
`fobi` int(8) NOT NULL default '0',
`myname` varchar(255) NOT NULL default '',
`mymoney` int(8) NOT NULL default '0',
`deposit` int(8) NOT NULL default '0',
`renhp` int(8) NOT NULL default '0',
`renmp` int(8) NOT NULL default '0',
`renexp` int(8) NOT NULL default '0',
`wbchouti` int(8) NOT NULL default '0',
`thex` varchar(255) NOT NULL default '',
`they` varchar(255) NOT NULL default '',
`openid` varchar(255) NOT NULL default '',
`access_token` varchar(255) NOT NULL default '',
`qqphoto` varchar(255) NOT NULL default '',
`province` varchar(255) NOT NULL default '',
`city` varchar(255) NOT NULL default '',
`area` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`content` mediumtext,
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}navbigclass" => "CREATE TABLE `{$mydbpre}navbigclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`navenglish` varchar(255) NOT NULL default '',
`navurl` varchar(255) NOT NULL default '',
`navtype` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`display` varchar(250) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`navtop` varchar(250) NOT NULL default '',
`navbuttom` varchar(250) NOT NULL default '',
`navleft` varchar(250) NOT NULL default '',
`navcontent` varchar(250) NOT NULL default '',
`navright` varchar(250) NOT NULL default '',
`navothre` varchar(250) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}navsmallclass" => "CREATE TABLE `{$mydbpre}navsmallclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`smallclassname` varchar(255) NOT NULL default '',
`navurl` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`navtitle` varchar(255) NOT NULL default '',
`navkeywords` varchar(255) NOT NULL default '',
`navdescription` varchar(255) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}onepage" => "CREATE TABLE `{$mydbpre}onepage` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`displaytitle` varchar(255) NOT NULL default '',
`adminid` int(8) NOT NULL default '0',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`sortrank` int(8) NOT NULL default '0',
`views` int(8) NOT NULL default '0',
`isrecommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`helptext` mediumtext,
`customaurl` varchar(255) NOT NULL default '',
`noteinfo` mediumtext,
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}onlineqq" => "CREATE TABLE `{$mydbpre}onlineqq` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`qq` varchar(255) NOT NULL default '',
`isonlinechat` varchar(250) NOT NULL default '',
`isaddfriend` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}payment" => "CREATE TABLE `{$mydbpre}payment` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(255) NOT NULL default '',
`memberid` varchar(255) NOT NULL default '',
`sex` varchar(255) NOT NULL default '',
`age` int(8) NOT NULL default '0',
`tel` varchar(255) NOT NULL default '',
`phone` varchar(255) NOT NULL default '',
`fax` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`zipcode` varchar(255) NOT NULL default '',
`address` varchar(255) NOT NULL default '',
`company` varchar(255) NOT NULL default '',
`qqmsn` varchar(255) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}previeworder" => "CREATE TABLE `{$mydbpre}previeworder` (
`id` int(5) unsigned NOT NULL auto_increment,
`memberid` varchar(255) NOT NULL default '',
`orderid` varchar(255) NOT NULL default '',
`productid` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`total` varchar(255) NOT NULL default '',
`price` int(8) NOT NULL default '0',
`productsum` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}product" => "CREATE TABLE `{$mydbpre}product` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`smallclassname` varchar(255) NOT NULL default '',
`threeclassname` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`recommend` varchar(250) NOT NULL default '',
`homerecommend` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`hot` varchar(250) NOT NULL default '',
`occasions` varchar(255) NOT NULL default '',
`hotline` varchar(255) NOT NULL default '',
`model` varchar(255) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`articlesource` varchar(255) NOT NULL default '',
`price` int(8) NOT NULL default '0',
`newprice` int(8) NOT NULL default '0',
`memberprice` int(8) NOT NULL default '0',
`sold` int(8) NOT NULL default '0',
`membertype` varchar(255) NOT NULL default '',
`memberuser` varchar(255) NOT NULL default '',
`hits` int(8) NOT NULL default '0',
`bigfiles` varchar(255) NOT NULL default '',
`smallfiles` varchar(255) NOT NULL default '',
`titlealt` varchar(255) NOT NULL default '',
`bigfilesalt` varchar(255) NOT NULL default '',
`smallfilesalt` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`productabout` mediumtext,
`articledescription` mediumtext,
`httpurl` varchar(255) NOT NULL default '',
`recordurl` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`ncount` int(8) NOT NULL default '0',
`x` int(8) NOT NULL default '0',
`y` int(8) NOT NULL default '0',
`infoid` int(8) NOT NULL default '0',
`wbchouti` int(8) NOT NULL default '0',
`expiretime` int(8) NOT NULL default '0',
`jinxinname` varchar(255) NOT NULL default '',
`articleinfostyle` varchar(255) NOT NULL default '',
`articleinfophotowidth` varchar(255) NOT NULL default '',
`articleinfophotoheight` varchar(255) NOT NULL default '',
`relatedtags` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}productcomment" => "CREATE TABLE `{$mydbpre}productcomment` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`pid` int(8) NOT NULL default '0',
`ptitle` varchar(255) NOT NULL default '',
`content` mediumtext,
`sort` int(8) NOT NULL default '0',
`ip` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}productparameter" => "CREATE TABLE `{$mydbpre}productparameter` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`pttitle` varchar(255) NOT NULL default '',
`ptstart` varchar(255) NOT NULL default '',
`ptend` varchar(255) NOT NULL default '',
`pid` int(8) NOT NULL default '0',
`homerecommend` varchar(250) NOT NULL default '',
`inforecommend` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`ptvalue1` varchar(255) NOT NULL default '',
`ptvalue2` varchar(255) NOT NULL default '',
`ptvalue3` varchar(255) NOT NULL default '',
`ptvalue4` varchar(255) NOT NULL default '',
`ptvalue5` varchar(255) NOT NULL default '',
`ptvalue6` varchar(255) NOT NULL default '',
`ptvalue7` varchar(255) NOT NULL default '',
`ptvalue8` varchar(255) NOT NULL default '',
`ptvalue9` varchar(255) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}qqmsn" => "CREATE TABLE `{$mydbpre}qqmsn` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`website` varchar(255) NOT NULL default '',
`tel` varchar(255) NOT NULL default '',
`qqnumber` varchar(255) NOT NULL default '',
`qqname` varchar(255) NOT NULL default '',
`msnnumber` varchar(255) NOT NULL default '',
`msnname` varchar(255) NOT NULL default '',
`qqstyle` int(8) NOT NULL default '0',
`qqpicture` int(8) NOT NULL default '0',
`display` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}searchstat" => "CREATE TABLE `{$mydbpre}searchstat` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`author` varchar(255) NOT NULL default '',
`sortrank` int(8) NOT NULL default '0',
`fontcolor` varchar(255) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`flags` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}smallclass" => "CREATE TABLE `{$mydbpre}smallclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`smallclassname` varchar(255) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`uploadfiles` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(255) NOT NULL default '',
`articlepagesize` varchar(255) NOT NULL default '',
`articleinfostyle` varchar(255) NOT NULL default '',
`articleinfophotowidth` varchar(255) NOT NULL default '',
`articleinfophotoheight` varchar(255) NOT NULL default '',
`addsorttype` varchar(255) NOT NULL default '',
`ordersorttype` varchar(255) NOT NULL default '',
`timesorttype` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}softtask" => "CREATE TABLE `{$mydbpre}softtask` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`content` mediumtext,
`filepath` varchar(255) NOT NULL default '',
`nsort` int(8) NOT NULL default '0',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}tablecomment" => "CREATE TABLE `{$mydbpre}tablecomment` (
`id` int(5) unsigned NOT NULL auto_increment,
`userid` int(8) NOT NULL default '0',
`itemid` int(8) NOT NULL default '0',
`parentid` int(8) NOT NULL default '0',
`tablename` varchar(255) NOT NULL default '',
`username` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`tel` varchar(255) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`reply` mediumtext,
`noteinfo` mediumtext,
`through` int(8) NOT NULL default '0',
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}templatemodule" => "CREATE TABLE `{$mydbpre}templatemodule` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`showtitle` varchar(255) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`recommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`helpmsg` varchar(255) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}threeclass" => "CREATE TABLE `{$mydbpre}threeclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`smallclassname` varchar(255) NOT NULL default '',
`threeclassname` varchar(255) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(255) NOT NULL default '',
`articlepagesize` varchar(255) NOT NULL default '',
`articleinfostyle` varchar(255) NOT NULL default '',
`articleinfophotowidth` varchar(255) NOT NULL default '',
`articleinfophotoheight` varchar(255) NOT NULL default '',
`addsorttype` varchar(255) NOT NULL default '',
`ordersorttype` varchar(255) NOT NULL default '',
`timesorttype` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}vote" => "CREATE TABLE `{$mydbpre}vote` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`option1` varchar(255) NOT NULL default '',
`option2` varchar(255) NOT NULL default '',
`option3` varchar(255) NOT NULL default '',
`option4` varchar(255) NOT NULL default '',
`option5` varchar(255) NOT NULL default '',
`option6` varchar(255) NOT NULL default '',
`num1` int(8) NOT NULL default '0',
`num2` int(8) NOT NULL default '0',
`num3` int(8) NOT NULL default '0',
`num4` int(8) NOT NULL default '0',
`num5` int(8) NOT NULL default '0',
`num6` int(8) NOT NULL default '0',
`display` varchar(250) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`votetype` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}watermark" => "CREATE TABLE `{$mydbpre}watermark` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`watermarktext` varchar(255) NOT NULL default '',
`watermarktextposition` varchar(255) NOT NULL default '',
`textx` int(8) NOT NULL default '0',
`texty` int(8) NOT NULL default '0',
`ntextsize` int(8) NOT NULL default '0',
`textrotation` int(8) NOT NULL default '0',
`textcolor` varchar(255) NOT NULL default '',
`watermarktypeface` varchar(255) NOT NULL default '',
`watermarkimgpath` varchar(255) NOT NULL default '',
`watermarkimgposition` varchar(255) NOT NULL default '',
`imgx` int(8) NOT NULL default '0',
`imgy` int(8) NOT NULL default '0',
`watermarkimgtransparency` int(8) NOT NULL default '0',
`zoomwidth` int(8) NOT NULL default '0',
`zoomheight` int(8) NOT NULL default '0',
`nsort` int(8) NOT NULL default '0',
`content` mediumtext,
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}webcolumn" => "CREATE TABLE `{$mydbpre}webcolumn` (
`id` int(5) unsigned NOT NULL auto_increment,
`columnname` varchar(255) NOT NULL default '',
`columnenname` varchar(255) NOT NULL default '',
`columntype` varchar(255) NOT NULL default '',
`parentid` int(8) NOT NULL default '0',
`topid` int(8) NOT NULL default '0',
`sortrank` int(8) NOT NULL default '0',
`views` int(8) NOT NULL default '0',
`adminid` int(8) NOT NULL default '0',
`isdisplay` varchar(250) NOT NULL default '',
`smallimage` varchar(255) NOT NULL default '',
`bigimage` varchar(255) NOT NULL default '',
`bannerimage` varchar(255) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`showtitle` varchar(255) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`ismakehtml` varchar(250) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`npagesize` int(8) NOT NULL default '0',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`noteinfo` mediumtext,
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}weblayout" => "CREATE TABLE `{$mydbpre}weblayout` (
`id` int(5) unsigned NOT NULL auto_increment,
`layoutname` varchar(255) NOT NULL default '',
`layoutlist` varchar(255) NOT NULL default '',
`replacestyle` varchar(255) NOT NULL default '',
`actioncontent` mediumtext,
`sortrank` int(8) NOT NULL default '0',
`isdisplay` varchar(250) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` int(8) NOT NULL default '0',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}weblink" => "CREATE TABLE `{$mydbpre}weblink` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`content` mediumtext,
`sort` int(8) NOT NULL default '0',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}webmodule" => "CREATE TABLE `{$mydbpre}webmodule` (
`id` int(5) unsigned NOT NULL auto_increment,
`moduletype` varchar(255) NOT NULL default '',
`modulename` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`sortrank` int(8) NOT NULL default '0',
`isdisplay` varchar(250) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` int(8) NOT NULL default '0',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}website" => "CREATE TABLE `{$mydbpre}website` (
`id` int(5) unsigned NOT NULL auto_increment,
`websiteurl` varchar(255) NOT NULL default '',
`websitebottom` mediumtext,
`websiteflow` int(8) NOT NULL default '0',
`websiteflowstyle` int(8) NOT NULL default '0',
`websiteflowmedian` int(8) NOT NULL default '0',
`productlist` varchar(255) NOT NULL default '',
`newslist` varchar(255) NOT NULL default '',
`newsdid` varchar(255) NOT NULL default '',
`tz51la` varchar(255) NOT NULL default '',
`useremail` varchar(255) NOT NULL default '',
`productdid` varchar(255) NOT NULL default '',
`templateindex` mediumtext,
`templatehome` mediumtext,
`templatemain` mediumtext,
`templatemain2` mediumtext,
`templatemain3` mediumtext,
`usenumb` mediumtext,
`webrecord` varchar(255) NOT NULL default '',
`contentwebrecord` mediumtext,
`usehttpurl` varchar(255) NOT NULL default '',
`tempusehttpurl` mediumtext,
`webdate` varchar(250) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`webtemplate` varchar(255) NOT NULL default '',
`webskins` varchar(255) NOT NULL default '',
`webfoldername` varchar(255) NOT NULL default '',
`webimages` varchar(255) NOT NULL default '',
`webcss` varchar(255) NOT NULL default '',
`webjs` varchar(255) NOT NULL default '',
`addwebsite` varchar(250) NOT NULL default '',
`updatehtml` varchar(250) NOT NULL default '',
`ishtmlformatting` varchar(250) NOT NULL default '',
`isweblabelclose` varchar(250) NOT NULL default '',
`iscntoen` varchar(250) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`moduleskins` varchar(255) NOT NULL default '',
`findtpl` varchar(255) NOT NULL default '',
`replacetpl` varchar(255) NOT NULL default '',
`webcodefindtpl` varchar(255) NOT NULL default '',
`webcodereplacetpl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`webhtml` varchar(255) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}websitestat" => "CREATE TABLE `{$mydbpre}websitestat` (
`id` int(5) unsigned NOT NULL auto_increment,
`visiturl` mediumtext,
`viewurl` mediumtext,
`browser` varchar(255) NOT NULL default '',
`operatingsystem` varchar(255) NOT NULL default '',
`screenwh` varchar(255) NOT NULL default '',
`moreinfo` varchar(255) NOT NULL default '',
`viewdatetime` varchar(250) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`dateclass` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` int(8) NOT NULL default '0',
`noteinfo` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}webtemplate" => "CREATE TABLE `{$mydbpre}webtemplate` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`bigclassname` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`mbparameter` mediumtext,
`recommend` varchar(250) NOT NULL default '',
`mbupdate` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_admin" => "CREATE TABLE `{$mydbpre}xy_admin` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(255) NOT NULL default '',
`pwd` varchar(255) NOT NULL default '',
`pseudonym` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`regip` varchar(255) NOT NULL default '',
`upip` varchar(255) NOT NULL default '',
`quanxian` mediumtext,
`verificationmode` int(8) NOT NULL default '0',
`adminlevel` varchar(255) NOT NULL default '',
`channel` varchar(255) NOT NULL default '',
`mtest` varchar(250) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_articledetail" => "CREATE TABLE `{$mydbpre}xy_articledetail` (
`id` int(5) unsigned NOT NULL auto_increment,
`parentid` int(8) NOT NULL default '0',
`topid` int(8) NOT NULL default '0',
`sortrank` int(8) NOT NULL default '0',
`views` int(8) NOT NULL default '0',
`adminid` int(8) NOT NULL default '0',
`smallimage` varchar(255) NOT NULL default '',
`bigimage` varchar(255) NOT NULL default '',
`bannerimage` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`titlecolor` varchar(255) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`ischeck` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`occasions` varchar(255) NOT NULL default '',
`hotline` varchar(255) NOT NULL default '',
`model` varchar(255) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`articlesource` varchar(255) NOT NULL default '',
`price` int(8) NOT NULL default '0',
`newprice` int(8) NOT NULL default '0',
`memberprice` int(8) NOT NULL default '0',
`sold` int(8) NOT NULL default '0',
`membertype` varchar(255) NOT NULL default '',
`memberuser` varchar(255) NOT NULL default '',
`hits` int(8) NOT NULL default '0',
`titlealt` varchar(255) NOT NULL default '',
`bigfilesalt` varchar(255) NOT NULL default '',
`smallfilesalt` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`productabout` mediumtext,
`articledescription` mediumtext,
`httpurl` varchar(255) NOT NULL default '',
`recordurl` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`flags` varchar(255) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`ncount` int(8) NOT NULL default '0',
`articleinfostyle` varchar(255) NOT NULL default '',
`articleinfophotowidth` varchar(255) NOT NULL default '',
`articleinfophotoheight` varchar(255) NOT NULL default '',
`relatedtags` varchar(255) NOT NULL default '',
`weight` int(8) NOT NULL default '0',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`noteinfo` mediumtext,
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_bidding" => "CREATE TABLE `{$mydbpre}xy_bidding` (
`id` int(5) unsigned NOT NULL auto_increment,
`searchwords` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`showreason` varchar(255) NOT NULL default '',
`ncomputersearch` int(8) NOT NULL default '0',
`nmobliesearch` int(8) NOT NULL default '0',
`ncountsearch` int(8) NOT NULL default '0',
`nwordprice` int(8) NOT NULL default '0',
`ndegree` int(8) NOT NULL default '0',
`sortrank` int(8) NOT NULL default '0',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_bigclass" => "CREATE TABLE `{$mydbpre}xy_bigclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(255) NOT NULL default '',
`articlepagesize` varchar(255) NOT NULL default '',
`articleinfostyle` varchar(255) NOT NULL default '',
`articleinfophotowidth` varchar(255) NOT NULL default '',
`articleinfophotoheight` varchar(255) NOT NULL default '',
`addsorttype` varchar(255) NOT NULL default '',
`ordersorttype` varchar(255) NOT NULL default '',
`timesorttype` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_feedback" => "CREATE TABLE `{$mydbpre}xy_feedback` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`guestname` varchar(255) NOT NULL default '',
`tel` varchar(255) NOT NULL default '',
`fax` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`mobile` varchar(255) NOT NULL default '',
`qq` varchar(255) NOT NULL default '',
`msn` varchar(255) NOT NULL default '',
`company` varchar(255) NOT NULL default '',
`address` varchar(255) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_friendlink" => "CREATE TABLE `{$mydbpre}xy_friendlink` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`alt` varchar(255) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`nofollow` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_front" => "CREATE TABLE `{$mydbpre}xy_front` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`content` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_guestbook" => "CREATE TABLE `{$mydbpre}xy_guestbook` (
`id` int(5) unsigned NOT NULL auto_increment,
`guestname` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`tel` varchar(255) NOT NULL default '',
`qq` varchar(255) NOT NULL default '',
`msn` varchar(255) NOT NULL default '',
`face` int(8) NOT NULL default '0',
`through` varchar(250) NOT NULL default '',
`address` varchar(255) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`reply` mediumtext,
`fozu` varchar(255) NOT NULL default '',
`toname` varchar(255) NOT NULL default '',
`tomail` varchar(255) NOT NULL default '',
`tophone` varchar(255) NOT NULL default '',
`myname` varchar(255) NOT NULL default '',
`mymail` varchar(255) NOT NULL default '',
`myphone` varchar(255) NOT NULL default '',
`mycontent` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_inputconfig" => "CREATE TABLE `{$mydbpre}xy_inputconfig` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`fronttitle` varchar(255) NOT NULL default '',
`backendtitle` varchar(255) NOT NULL default '',
`fieldname` varchar(255) NOT NULL default '',
`customfieldname` varchar(255) NOT NULL default '',
`inputtype` varchar(255) NOT NULL default '',
`inputwidth` varchar(255) NOT NULL default '',
`inputheight` varchar(255) NOT NULL default '',
`verificationtype` varchar(255) NOT NULL default '',
`verificationmsg` varchar(255) NOT NULL default '',
`tipstext` varchar(255) NOT NULL default '',
`defaultvalue` varchar(255) NOT NULL default '',
`placeholder` varchar(255) NOT NULL default '',
`listshow` varchar(250) NOT NULL default '',
`editdialogshow` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`through` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_inputvalue" => "CREATE TABLE `{$mydbpre}xy_inputvalue` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`str1` varchar(255) NOT NULL default '',
`str2` varchar(255) NOT NULL default '',
`str3` varchar(255) NOT NULL default '',
`str4` varchar(255) NOT NULL default '',
`str5` varchar(255) NOT NULL default '',
`str6` varchar(255) NOT NULL default '',
`str7` varchar(255) NOT NULL default '',
`str8` varchar(255) NOT NULL default '',
`str9` varchar(255) NOT NULL default '',
`str10` varchar(255) NOT NULL default '',
`str11` varchar(255) NOT NULL default '',
`str12` varchar(255) NOT NULL default '',
`str13` varchar(255) NOT NULL default '',
`str14` varchar(255) NOT NULL default '',
`str15` varchar(255) NOT NULL default '',
`numb1` int(8) NOT NULL default '0',
`numb2` int(8) NOT NULL default '0',
`numb3` int(8) NOT NULL default '0',
`numb4` int(8) NOT NULL default '0',
`numb5` int(8) NOT NULL default '0',
`numb6` int(8) NOT NULL default '0',
`numb7` int(8) NOT NULL default '0',
`numb8` int(8) NOT NULL default '0',
`numb9` int(8) NOT NULL default '0',
`truefalse1` varchar(250) NOT NULL default '',
`truefalse2` varchar(250) NOT NULL default '',
`truefalse3` varchar(250) NOT NULL default '',
`truefalse4` varchar(250) NOT NULL default '',
`truefalse5` varchar(250) NOT NULL default '',
`truefalse6` varchar(250) NOT NULL default '',
`truefalse7` varchar(250) NOT NULL default '',
`truefalse8` varchar(250) NOT NULL default '',
`truefalse9` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`through` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_job" => "CREATE TABLE `{$mydbpre}xy_job` (
`id` int(5) unsigned NOT NULL auto_increment,
`sex` varchar(255) NOT NULL default '',
`age` varchar(255) NOT NULL default '',
`education` varchar(255) NOT NULL default '',
`workarea` varchar(255) NOT NULL default '',
`post` varchar(255) NOT NULL default '',
`monthly` varchar(255) NOT NULL default '',
`startdatetime` varchar(255) NOT NULL default '',
`enddatetime` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_listmenu" => "CREATE TABLE `{$mydbpre}xy_listmenu` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`smallclassname` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`display` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_maininfo" => "CREATE TABLE `{$mydbpre}xy_maininfo` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`showtitle` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`recommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`helptext` mediumtext,
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_member" => "CREATE TABLE `{$mydbpre}xy_member` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`username` varchar(255) NOT NULL default '',
`pwd` varchar(255) NOT NULL default '',
`yunpwd` varchar(255) NOT NULL default '',
`sex` varchar(255) NOT NULL default '',
`age` int(8) NOT NULL default '0',
`tel` varchar(255) NOT NULL default '',
`phone` varchar(255) NOT NULL default '',
`fax` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`zipcode` varchar(255) NOT NULL default '',
`address` varchar(255) NOT NULL default '',
`company` varchar(255) NOT NULL default '',
`regip` varchar(255) NOT NULL default '',
`logip` varchar(255) NOT NULL default '',
`loginnumb` int(8) NOT NULL default '0',
`logintime` varchar(250) NOT NULL default '',
`lastlogintime` varchar(250) NOT NULL default '',
`scene` varchar(255) NOT NULL default '',
`scenemap` varchar(255) NOT NULL default '',
`renjb` int(8) NOT NULL default '0',
`fobi` int(8) NOT NULL default '0',
`myname` varchar(255) NOT NULL default '',
`mymoney` int(8) NOT NULL default '0',
`deposit` int(8) NOT NULL default '0',
`renhp` int(8) NOT NULL default '0',
`renmp` int(8) NOT NULL default '0',
`renexp` int(8) NOT NULL default '0',
`wbchouti` int(8) NOT NULL default '0',
`thex` varchar(255) NOT NULL default '',
`they` varchar(255) NOT NULL default '',
`openid` varchar(255) NOT NULL default '',
`access_token` varchar(255) NOT NULL default '',
`qqphoto` varchar(255) NOT NULL default '',
`province` varchar(255) NOT NULL default '',
`city` varchar(255) NOT NULL default '',
`area` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`content` mediumtext,
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_navbigclass" => "CREATE TABLE `{$mydbpre}xy_navbigclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`navenglish` varchar(255) NOT NULL default '',
`navurl` varchar(255) NOT NULL default '',
`navtype` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`display` varchar(250) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`navtop` varchar(250) NOT NULL default '',
`navbuttom` varchar(250) NOT NULL default '',
`navleft` varchar(250) NOT NULL default '',
`navcontent` varchar(250) NOT NULL default '',
`navright` varchar(250) NOT NULL default '',
`navothre` varchar(250) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_navsmallclass" => "CREATE TABLE `{$mydbpre}xy_navsmallclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`smallclassname` varchar(255) NOT NULL default '',
`navurl` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`navtitle` varchar(255) NOT NULL default '',
`navkeywords` varchar(255) NOT NULL default '',
`navdescription` varchar(255) NOT NULL default '',
`display` varchar(250) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_onepage" => "CREATE TABLE `{$mydbpre}xy_onepage` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`displaytitle` varchar(255) NOT NULL default '',
`adminid` int(8) NOT NULL default '0',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`sortrank` int(8) NOT NULL default '0',
`views` int(8) NOT NULL default '0',
`isrecommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`helptext` mediumtext,
`customaurl` varchar(255) NOT NULL default '',
`noteinfo` mediumtext,
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_onlineqq" => "CREATE TABLE `{$mydbpre}xy_onlineqq` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`qq` varchar(255) NOT NULL default '',
`isonlinechat` varchar(250) NOT NULL default '',
`isaddfriend` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_payment" => "CREATE TABLE `{$mydbpre}xy_payment` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(255) NOT NULL default '',
`memberid` varchar(255) NOT NULL default '',
`sex` varchar(255) NOT NULL default '',
`age` int(8) NOT NULL default '0',
`tel` varchar(255) NOT NULL default '',
`phone` varchar(255) NOT NULL default '',
`fax` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`zipcode` varchar(255) NOT NULL default '',
`address` varchar(255) NOT NULL default '',
`company` varchar(255) NOT NULL default '',
`qqmsn` varchar(255) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_previeworder" => "CREATE TABLE `{$mydbpre}xy_previeworder` (
`id` int(5) unsigned NOT NULL auto_increment,
`memberid` varchar(255) NOT NULL default '',
`orderid` varchar(255) NOT NULL default '',
`productid` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`total` varchar(255) NOT NULL default '',
`price` int(8) NOT NULL default '0',
`productsum` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_product" => "CREATE TABLE `{$mydbpre}xy_product` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`smallclassname` varchar(255) NOT NULL default '',
`threeclassname` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`recommend` varchar(250) NOT NULL default '',
`homerecommend` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`hot` varchar(250) NOT NULL default '',
`occasions` varchar(255) NOT NULL default '',
`hotline` varchar(255) NOT NULL default '',
`model` varchar(255) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`articlesource` varchar(255) NOT NULL default '',
`price` int(8) NOT NULL default '0',
`newprice` int(8) NOT NULL default '0',
`memberprice` int(8) NOT NULL default '0',
`sold` int(8) NOT NULL default '0',
`membertype` varchar(255) NOT NULL default '',
`memberuser` varchar(255) NOT NULL default '',
`hits` int(8) NOT NULL default '0',
`bigfiles` varchar(255) NOT NULL default '',
`smallfiles` varchar(255) NOT NULL default '',
`titlealt` varchar(255) NOT NULL default '',
`bigfilesalt` varchar(255) NOT NULL default '',
`smallfilesalt` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`productabout` mediumtext,
`articledescription` mediumtext,
`httpurl` varchar(255) NOT NULL default '',
`recordurl` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`ncount` int(8) NOT NULL default '0',
`x` int(8) NOT NULL default '0',
`y` int(8) NOT NULL default '0',
`infoid` int(8) NOT NULL default '0',
`wbchouti` int(8) NOT NULL default '0',
`expiretime` int(8) NOT NULL default '0',
`jinxinname` varchar(255) NOT NULL default '',
`articleinfostyle` varchar(255) NOT NULL default '',
`articleinfophotowidth` varchar(255) NOT NULL default '',
`articleinfophotoheight` varchar(255) NOT NULL default '',
`relatedtags` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_productcomment" => "CREATE TABLE `{$mydbpre}xy_productcomment` (
`id` int(5) unsigned NOT NULL auto_increment,
`username` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`pid` int(8) NOT NULL default '0',
`ptitle` varchar(255) NOT NULL default '',
`content` mediumtext,
`sort` int(8) NOT NULL default '0',
`ip` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_productparameter" => "CREATE TABLE `{$mydbpre}xy_productparameter` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`pttitle` varchar(255) NOT NULL default '',
`ptstart` varchar(255) NOT NULL default '',
`ptend` varchar(255) NOT NULL default '',
`pid` int(8) NOT NULL default '0',
`homerecommend` varchar(250) NOT NULL default '',
`inforecommend` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`ptvalue1` varchar(255) NOT NULL default '',
`ptvalue2` varchar(255) NOT NULL default '',
`ptvalue3` varchar(255) NOT NULL default '',
`ptvalue4` varchar(255) NOT NULL default '',
`ptvalue5` varchar(255) NOT NULL default '',
`ptvalue6` varchar(255) NOT NULL default '',
`ptvalue7` varchar(255) NOT NULL default '',
`ptvalue8` varchar(255) NOT NULL default '',
`ptvalue9` varchar(255) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_qqmsn" => "CREATE TABLE `{$mydbpre}xy_qqmsn` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`website` varchar(255) NOT NULL default '',
`tel` varchar(255) NOT NULL default '',
`qqnumber` varchar(255) NOT NULL default '',
`qqname` varchar(255) NOT NULL default '',
`msnnumber` varchar(255) NOT NULL default '',
`msnname` varchar(255) NOT NULL default '',
`qqstyle` int(8) NOT NULL default '0',
`qqpicture` int(8) NOT NULL default '0',
`display` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_searchstat" => "CREATE TABLE `{$mydbpre}xy_searchstat` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`author` varchar(255) NOT NULL default '',
`sortrank` int(8) NOT NULL default '0',
`fontcolor` varchar(255) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`flags` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_smallclass" => "CREATE TABLE `{$mydbpre}xy_smallclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`smallclassname` varchar(255) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`uploadfiles` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(255) NOT NULL default '',
`articlepagesize` varchar(255) NOT NULL default '',
`articleinfostyle` varchar(255) NOT NULL default '',
`articleinfophotowidth` varchar(255) NOT NULL default '',
`articleinfophotoheight` varchar(255) NOT NULL default '',
`addsorttype` varchar(255) NOT NULL default '',
`ordersorttype` varchar(255) NOT NULL default '',
`timesorttype` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_softtask" => "CREATE TABLE `{$mydbpre}xy_softtask` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`content` mediumtext,
`filepath` varchar(255) NOT NULL default '',
`nsort` int(8) NOT NULL default '0',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_tablecomment" => "CREATE TABLE `{$mydbpre}xy_tablecomment` (
`id` int(5) unsigned NOT NULL auto_increment,
`userid` int(8) NOT NULL default '0',
`itemid` int(8) NOT NULL default '0',
`parentid` int(8) NOT NULL default '0',
`tablename` varchar(255) NOT NULL default '',
`username` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`email` varchar(255) NOT NULL default '',
`tel` varchar(255) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`reply` mediumtext,
`noteinfo` mediumtext,
`through` int(8) NOT NULL default '0',
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_templatemodule" => "CREATE TABLE `{$mydbpre}xy_templatemodule` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`showtitle` varchar(255) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`recommend` varchar(250) NOT NULL default '',
`dispalyeditor` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`helpmsg` varchar(255) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_threeclass" => "CREATE TABLE `{$mydbpre}xy_threeclass` (
`id` int(5) unsigned NOT NULL auto_increment,
`bigclassname` varchar(255) NOT NULL default '',
`smallclassname` varchar(255) NOT NULL default '',
`threeclassname` varchar(255) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`onhtml` varchar(250) NOT NULL default '',
`articleliststyle` varchar(255) NOT NULL default '',
`articlepagesize` varchar(255) NOT NULL default '',
`articleinfostyle` varchar(255) NOT NULL default '',
`articleinfophotowidth` varchar(255) NOT NULL default '',
`articleinfophotoheight` varchar(255) NOT NULL default '',
`addsorttype` varchar(255) NOT NULL default '',
`ordersorttype` varchar(255) NOT NULL default '',
`timesorttype` varchar(255) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_vote" => "CREATE TABLE `{$mydbpre}xy_vote` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`option1` varchar(255) NOT NULL default '',
`option2` varchar(255) NOT NULL default '',
`option3` varchar(255) NOT NULL default '',
`option4` varchar(255) NOT NULL default '',
`option5` varchar(255) NOT NULL default '',
`option6` varchar(255) NOT NULL default '',
`num1` int(8) NOT NULL default '0',
`num2` int(8) NOT NULL default '0',
`num3` int(8) NOT NULL default '0',
`num4` int(8) NOT NULL default '0',
`num5` int(8) NOT NULL default '0',
`num6` int(8) NOT NULL default '0',
`display` varchar(250) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`banner` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`onhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`votetype` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_watermark" => "CREATE TABLE `{$mydbpre}xy_watermark` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`watermarktext` varchar(255) NOT NULL default '',
`watermarktextposition` varchar(255) NOT NULL default '',
`textx` int(8) NOT NULL default '0',
`texty` int(8) NOT NULL default '0',
`ntextsize` int(8) NOT NULL default '0',
`textrotation` int(8) NOT NULL default '0',
`textcolor` varchar(255) NOT NULL default '',
`watermarktypeface` varchar(255) NOT NULL default '',
`watermarkimgpath` varchar(255) NOT NULL default '',
`watermarkimgposition` varchar(255) NOT NULL default '',
`imgx` int(8) NOT NULL default '0',
`imgy` int(8) NOT NULL default '0',
`watermarkimgtransparency` int(8) NOT NULL default '0',
`zoomwidth` int(8) NOT NULL default '0',
`zoomheight` int(8) NOT NULL default '0',
`nsort` int(8) NOT NULL default '0',
`content` mediumtext,
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_webcolumn" => "CREATE TABLE `{$mydbpre}xy_webcolumn` (
`id` int(5) unsigned NOT NULL auto_increment,
`columnname` varchar(255) NOT NULL default '',
`columnenname` varchar(255) NOT NULL default '',
`columntype` varchar(255) NOT NULL default '',
`parentid` int(8) NOT NULL default '0',
`topid` int(8) NOT NULL default '0',
`sortrank` int(8) NOT NULL default '0',
`views` int(8) NOT NULL default '0',
`adminid` int(8) NOT NULL default '0',
`isdisplay` varchar(250) NOT NULL default '',
`smallimage` varchar(255) NOT NULL default '',
`bigimage` varchar(255) NOT NULL default '',
`bannerimage` varchar(255) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`showtitle` varchar(255) NOT NULL default '',
`labletitle` varchar(255) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`foldername` varchar(255) NOT NULL default '',
`filename` varchar(255) NOT NULL default '',
`templatepath` varchar(255) NOT NULL default '',
`target` varchar(255) NOT NULL default '',
`nofollow` int(8) NOT NULL default '0',
`fontcolor` varchar(255) NOT NULL default '',
`fontb` varchar(250) NOT NULL default '',
`ismakehtml` varchar(250) NOT NULL default '',
`topmodule` varchar(255) NOT NULL default '',
`bottommodule` varchar(255) NOT NULL default '',
`leftmodule` varchar(255) NOT NULL default '',
`middlemodule` varchar(255) NOT NULL default '',
`rightmodule` varchar(255) NOT NULL default '',
`customaurl` varchar(255) NOT NULL default '',
`npagesize` int(8) NOT NULL default '0',
`ishtml` varchar(250) NOT NULL default '',
`isonhtml` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`noteinfo` mediumtext,
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_weblayout" => "CREATE TABLE `{$mydbpre}xy_weblayout` (
`id` int(5) unsigned NOT NULL auto_increment,
`layoutname` varchar(255) NOT NULL default '',
`layoutlist` varchar(255) NOT NULL default '',
`replacestyle` varchar(255) NOT NULL default '',
`actioncontent` mediumtext,
`sortrank` int(8) NOT NULL default '0',
`isdisplay` varchar(250) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` int(8) NOT NULL default '0',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_weblink" => "CREATE TABLE `{$mydbpre}xy_weblink` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`url` varchar(255) NOT NULL default '',
`imgpath` varchar(255) NOT NULL default '',
`content` mediumtext,
`sort` int(8) NOT NULL default '0',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` varchar(250) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_webmodule" => "CREATE TABLE `{$mydbpre}xy_webmodule` (
`id` int(5) unsigned NOT NULL auto_increment,
`moduletype` varchar(255) NOT NULL default '',
`modulename` varchar(255) NOT NULL default '',
`title` varchar(255) NOT NULL default '',
`sortrank` int(8) NOT NULL default '0',
`isdisplay` varchar(250) NOT NULL default '',
`author` varchar(255) NOT NULL default '',
`views` int(8) NOT NULL default '0',
`adminid` int(8) NOT NULL default '0',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`simpleintroduction` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_website" => "CREATE TABLE `{$mydbpre}xy_website` (
`id` int(5) unsigned NOT NULL auto_increment,
`websiteurl` varchar(255) NOT NULL default '',
`websitebottom` mediumtext,
`websiteflow` int(8) NOT NULL default '0',
`websiteflowstyle` int(8) NOT NULL default '0',
`websiteflowmedian` int(8) NOT NULL default '0',
`productlist` varchar(255) NOT NULL default '',
`newslist` varchar(255) NOT NULL default '',
`newsdid` varchar(255) NOT NULL default '',
`tz51la` varchar(255) NOT NULL default '',
`useremail` varchar(255) NOT NULL default '',
`productdid` varchar(255) NOT NULL default '',
`templateindex` mediumtext,
`templatehome` mediumtext,
`templatemain` mediumtext,
`templatemain2` mediumtext,
`templatemain3` mediumtext,
`usenumb` mediumtext,
`webrecord` varchar(255) NOT NULL default '',
`contentwebrecord` mediumtext,
`usehttpurl` varchar(255) NOT NULL default '',
`tempusehttpurl` mediumtext,
`webdate` varchar(250) NOT NULL default '',
`webtitle` varchar(255) NOT NULL default '',
`webkeywords` varchar(255) NOT NULL default '',
`webdescription` varchar(255) NOT NULL default '',
`webtemplate` varchar(255) NOT NULL default '',
`webskins` varchar(255) NOT NULL default '',
`webfoldername` varchar(255) NOT NULL default '',
`webimages` varchar(255) NOT NULL default '',
`webcss` varchar(255) NOT NULL default '',
`webjs` varchar(255) NOT NULL default '',
`addwebsite` varchar(250) NOT NULL default '',
`updatehtml` varchar(250) NOT NULL default '',
`ishtmlformatting` varchar(250) NOT NULL default '',
`isweblabelclose` varchar(250) NOT NULL default '',
`iscntoen` varchar(250) NOT NULL default '',
`flags` varchar(255) NOT NULL default '',
`moduleskins` varchar(255) NOT NULL default '',
`findtpl` varchar(255) NOT NULL default '',
`replacetpl` varchar(255) NOT NULL default '',
`webcodefindtpl` varchar(255) NOT NULL default '',
`webcodereplacetpl` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`webhtml` varchar(255) NOT NULL default '',
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_websitestat" => "CREATE TABLE `{$mydbpre}xy_websitestat` (
`id` int(5) unsigned NOT NULL auto_increment,
`visiturl` mediumtext,
`viewurl` mediumtext,
`browser` varchar(255) NOT NULL default '',
`operatingsystem` varchar(255) NOT NULL default '',
`screenwh` varchar(255) NOT NULL default '',
`moreinfo` varchar(255) NOT NULL default '',
`viewdatetime` varchar(250) NOT NULL default '',
`ip` varchar(255) NOT NULL default '',
`dateclass` varchar(255) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`through` int(8) NOT NULL default '0',
`noteinfo` mediumtext,
`bodycontent` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
"{$mydbpre}xy_webtemplate" => "CREATE TABLE `{$mydbpre}xy_webtemplate` (
`id` int(5) unsigned NOT NULL auto_increment,
`title` varchar(255) NOT NULL default '',
`bigclassname` varchar(255) NOT NULL default '',
`sort` int(8) NOT NULL default '0',
`mbparameter` mediumtext,
`recommend` varchar(250) NOT NULL default '',
`mbupdate` varchar(250) NOT NULL default '',
`adddatetime` varchar(250) NOT NULL default '',
`updatetime` varchar(250) NOT NULL default '',
`content` mediumtext,
PRIMARY KEY  (`Id`)
){$char};",
//access end

	);
	
	
	foreach ($sqlTables as $tableName => $tableSql){
		$conn->query("DROP TABLE IF EXISTS {$tableName}");					//为删除表
		$conn->query($tableSql);											//为创建表
		echo("创建数据表 {$tableName} 成功>><br>");
	}
	echo('<a href="/admin/index.php">登录后台</a>');
	
    $conn->query('insert into admin (username,pwd,flags) values(\'admin\',\'' . myMD5('admin') . '\',\'|*|\')') ;
    $conn->query('insert into xy_admin (username,pwd,flags) values(\'admin\',\'' . myMD5('admin') . '\',\'|*|\')') ;
    $conn->query('insert into website (webtitle) values(\'默认\')') ;
    $conn->query('insert into xy_website (webtitle) values(\'默认\')') ;
	 
?>
 

